# Generated by Django 4.2.7 on 2024-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_booking_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
